# Generated by Django 5.0 on 2025-09-04 15:14

import django.core.validators
import relacionamentos.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the person', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('birthdate', models.DateField(help_text='Insert your birthday here.', verbose_name='Birthdate')),
                ('cpf', models.CharField(help_text='Insert your CPF Number without dots', max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.funcoes.validate_cpf])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
