# Generated by Django 5.0 on 2025-09-11 02:48

import django.core.validators
import django.db.models.deletion
import relacionamentos.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('edicao', models.CharField(max_length=100, verbose_name='Edição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reporter Name', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Reporter')),
                ('cpf', models.CharField(help_text='Insert your CPF Number without dots', max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.funcoes.validate_cpf])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('data_publicacao', models.DateField(verbose_name='Data de publicação')),
                ('magazines', models.ManyToManyField(to='relacionamentos.magazine')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter', verbose_name='Reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
