# Generated by Django 5.1.3 on 2025-09-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0002_magazine_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('pub_date', models.DateField(verbose_name='Data de publicação')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter', verbose_name='Reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.magazine')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='relacionamentos.Publication', to='relacionamentos.magazine'),
        ),
    ]
