# Generated by Django 5.0 on 2025-10-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0003_paper_publication_paper_magazines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.reporter', verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.reporter', verbose_name='Reporter'),
        ),
    ]
