# Generated by Django 5.0 on 2025-10-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0004_alter_article_reporter_alter_paper_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.magazine'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.paper'),
        ),
    ]
