# Generated by Django 5.0 on 2025-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0005_alter_publication_editor_alter_publication_magazine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'permissions': [('generate_code_exemplo', 'can generate new code')]},
        ),
        migrations.AlterField(
            model_name='paper',
            name='magazines',
            field=models.ManyToManyField(blank=True, through='relacionamentos.Publication', to='relacionamentos.magazine'),
        ),
    ]
