# Generated by Django 5.1.3 on 2025-08-28 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais R$.', max_digits=10, verbose_name='Valor')),
                ('turno', models.CharField(blank=True, max_length=8, null=True)),
                ('nota', models.FloatField(default=0.0)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('ingresso', models.BooleanField(default=False)),
                ('informacoes', models.TextField(blank=True, null=True)),
                ('guia', models.BooleanField(default=False)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('participantes', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(default='', max_length=100, verbose_name='Titulo')),
                ('data_avaliacao', models.DateField(default=datetime.date.today, verbose_name='Data da Avaliação')),
                ('data_visita', models.DateField(default=datetime.date.today, verbose_name='Data da Visita')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('nota', models.FloatField(default=0.0)),
                ('acompanhantes', models.CharField(blank=True, max_length=20, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('endereco', models.TextField(default='', verbose_name='Endereço')),
                ('nota', models.FloatField(default=0.0)),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento')),
                ('informacoes', models.TextField(blank=True, null=True, verbose_name='Informações')),
                ('ingresso', models.BooleanField(default=False, verbose_name='Ingresso')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais R$.', max_digits=10, verbose_name='Valor')),
                ('acessibilidade', models.BooleanField(default=False, verbose_name='Acessibilidade')),
                ('classificacao', models.IntegerField(default=0, verbose_name='Classificação')),
                ('contato', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('data_nascimento', models.DateField(help_text='Data de Nascimento', verbose_name='Data de Nascimento')),
                ('bio', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Biografia')),
                ('passaporte', models.TextField(max_length=255, verbose_name='Passaporte')),
                ('cidade', models.TextField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('pais', models.TextField(max_length=60, verbose_name='Pais')),
                ('genero', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT SPECIFIED', 'Não especificado')], default='NOT SPECIFIED', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tipo_refeicao', models.CharField(max_length=100, verbose_name='Tipo Refeicao')),
                ('faixa_de_preco', models.FloatField(default=0.0)),
                ('aceita_reserva', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
