# Generated by Django 5.0 on 2025-09-04 13:33

import aula.validators.cod
import aula.validators.funcoes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cod', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), aula.validators.cod.CodValidator('4444444444')])),
                ('name', models.CharField(max_length=255, unique=True)),
                ('genero', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT SPECIFIED', 'Não especificado')], default='NOT SPECIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='atividade',
            name='endereco',
            field=models.TextField(blank=True, null=True, validators=[aula.validators.cod.CodValidator()]),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nota',
            field=models.FloatField(default=0, validators=[aula.validators.funcoes.validate_par]),
        ),
    ]
