# Generated by Django 5.0 on 2025-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('genero', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT SPECIFIED', 'Não especificado')], default='NOT SPECIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
