# Generated by Django 5.0 on 2025-08-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_atividade_nota_atividade_preco_atividade_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='preco',
        ),
        migrations.AddField(
            model_name='atividade',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='guia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade',
            name='informacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='ingresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade',
            name='participantes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='atividade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais R$.', max_digits=10, verbose_name='Valor'),
        ),
    ]
