# Generated by Django 5.0 on 2025-08-27 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_avaliacao_local_remove_atividade_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='acompanhantes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_visita',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='titulo',
            field=models.CharField(default='', max_length=100, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='local',
            name='acessibilidade',
            field=models.BooleanField(default=False, verbose_name='Acessibilidade'),
        ),
        migrations.AddField(
            model_name='local',
            name='classificacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local',
            name='contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='endereco',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='local',
            name='horario_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='horario_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='informacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='ingresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='local',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='local',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais R$.', max_digits=10, verbose_name='Valor'),
        ),
    ]
