# Generated by Django 5.0 on 2025-08-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_avaliacao_acompanhantes_avaliacao_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tipo_refeicao', models.CharField(max_length=100, verbose_name='Tipo Refeicao')),
                ('faixa_de_preco', models.FloatField(default=0.0)),
                ('aceita_reserva', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
